In [103]:
"""
Характеристикой столбца целочисленной матрицы назовем сумму модулей его
отрицательных нечетных элементов. Переставляя столбцы заданной матрицы, расположить
их в соответствий с ростом характеристик. Найти сумму элементов в тех столбцах, которые
содержат хотя бы один отрицательный элемент.
"""

import numpy as np

a = -7
b = 7
n = int(input("Введите размер матрицы: "))
c = [0]*n

Matr = np.random.randint(a, b, (n, n))
print("Исходная таблица: ") 
print(Matr) 
k = 1
flag = int(1)
#print("Заполнение c")
for j in range(n):
    c[j]=0
    for i in range(n): 
        if ( Matr[i][j]<0 and Matr[i][j]%2!=0):
            c[j]+=abs(Matr[i][j])  
            
print("Матрица c:")
print(c)
while (flag==1):
    flag = 0
    for j in range (n-1):

        for j in range(1,n-1):    
            for k in range(n-j):
                if (c[k]>c[k+1]):
                    c[k],c[k+1] = c[k+1],c[k]
                    flag = 1
                    for i in range(n-1):
                        Matr[i][k],Matr[i][k+1] = Matr[i][k+1],Matr[i][k] 

print("Измененная матрица Matr:")                    
print(Matr) 
print("Измененная матрица c:")
print(c) 
#print(Matr[1][1])



Введите размер матрицы: 3
Исходная таблица: 
[[ 3 -5 -3]
 [ 2  6 -1]
 [-4  0 -2]]
Матрица c:
[0, 5, 4]
Измененная матрица Matr:
[[ 3 -3 -5]
 [ 2 -1  6]
 [-4  0 -2]]
Измененная матрица c:
[0, 4, 5]
